### ISSUE TITLE
SPF record type discontinued

### ISSUE THREAD

**Issue by nandosousafr** [trailofbits/spf-query#3]
Heys guys,

First of all, thank you for this incredible gem. It saved a lot of our time.

I've noticed that `spf-query` checks for SPF type records in https://github.com/trailofbits/spf-query/blob/master/lib/spf/query/query.rb#L23.

Since SPF record type was discontinued at [RFC 7208](https://tools.ietf.org/html/rfc7208#section-3.1), I think would a great idea to remove this verification or provide an alternative that allows us to skip it.

that make sense?

**Comment by postmodern** [comment]
I would like to keep it around for maximum coverage. We could move it to the bottom, as `_spf.example.com` is the defacto location for SPF records.

**Comment by nandosousafr** [comment]
@postmodern good idea. Just changing order works perfectly too.

I've opened two PR's with both skip and reorder approach. Thoughts?

**Comment by postmodern** [comment]
Merged. Adding options to enable/disable checking for SPF records in various places could be a different feature later on.

**Comment by nandosousafr** [comment]
Awesome. Thanks ;)

**Comment by nandosousafr** [comment]
bump the version ;) please?
