### ISSUE TITLE
Configurable DNS servers

### ISSUE THREAD

**Issue by adamlc** [trailofbits/spf-query#6]
It would be nice to have configurable DNS servers. Unfortunately I'm not a ruby dev but looking at the code it should be fairly easy (famous last words)!

:+1:

**Comment by postmodern** [comment]
We could support passing in your own instance of [Resolv::DNS](http://www.rubydoc.info/stdlib/resolv/Resolv/DNS#initialize-instance_method).

**Comment by postmodern** [comment]
Actually, we already support that!

    resolver = Resolv::DNS.new(nameserver: '8.8.8.8')
    SPF::Query::Record.query(..., resolver)

**Comment by adamlc** [comment]
Fantastic! Must have missed that, thanks!
